@AbapCatalog.viewEnhancementCategory: [#NONE]
@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'Test PO ITEMS'
@Metadata.ignorePropagatedAnnotations: true
@ObjectModel.usageType:{
    serviceQuality: #X,
    sizeCategory: #S,
    dataClass: #MIXED
}
define view entity ZPOITEM_TEST as select from I_PurchaseOrderItemAPI01
{
    key PurchaseOrder,
    key PurchaseOrderItem,
    PurchaseOrderItemUniqueID,
    PurchaseOrderCategory,
    DocumentCurrency,
    PurchasingDocumentDeletionCode,
    PurchasingDocumentItemOrigin,
    MaterialGroup,
    Material,
    MaterialType,
    SupplierMaterialNumber,
    SupplierSubrange,
    ManufacturerPartNmbr,
    Manufacturer,
    ManufacturerMaterial,
    PurchaseOrderItemText,
    ProductType,
    CompanyCode,
    Plant,
    ManualDeliveryAddressID,
    ReferenceDeliveryAddressID,
    Customer,
    Subcontractor,
    SupplierIsSubcontractor,
    CrossPlantConfigurableProduct,
    ArticleCategory,
    PlndOrderReplnmtElmntType,
    ProductPurchasePointsQtyUnit,
    StorageLocation,
    PurchaseOrderQuantityUnit,
    OrderItemQtyToBaseQtyNmrtr,
    OrderItemQtyToBaseQtyDnmntr,
    NetPriceQuantity,
    IsCompletelyDelivered,
    IsFinallyInvoiced,
    GoodsReceiptIsExpected,
    InvoiceIsExpected,
    InvoiceIsGoodsReceiptBased,
    PurchaseContractItem,
    PurchaseContract,
    PurchaseRequisition,
    RequirementTracking,
    PurchaseRequisitionItem,
    EvaldRcptSettlmtIsAllowed,
    UnlimitedOverdeliveryIsAllowed,
    OverdelivTolrtdLmtRatioInPct,
    UnderdelivTolrtdLmtRatioInPct,
    RequisitionerName,
    PlannedDeliveryDurationInDays,
    GoodsReceiptDurationInDays,
    PartialDeliveryIsAllowed,
    ConsumptionPosting,
    ServicePerformer,
    BaseUnit,
    PurchaseOrderItemCategory,
    ProfitCenter,
    OrderPriceUnit,
    ItemVolumeUnit,
    ItemWeightUnit,
    MultipleAcctAssgmtDistribution,
    PartialInvoiceDistribution,
    PricingDateControl,
    IsStatisticalItem,
    PurchasingParentItem,
    GoodsReceiptLatestCreationDate,
    IsReturnsItem,
    PurchasingOrderReason,
    IncotermsClassification,
    IncotermsTransferLocation,
    IncotermsLocation1,
    IncotermsLocation2,
    PriorSupplier,
    InternationalArticleNumber,
    IntrastatServiceCode,
    CommodityCode,
    MaterialFreightGroup,
    DiscountInKindEligibility,
    PurgItemIsBlockedForDelivery,
    SupplierConfirmationControlKey,
    PriceIsToBePrinted,
    AccountAssignmentCategory
}
