CLASS zbp_idd_quote_comparison DEFINITION PUBLIC FINAL for BEHAVIOR OF ZIDD_QUOTE_COMPARISON.
*  CREATE PUBLIC .
*
*  PUBLIC SECTION.
*  PROTECTED SECTION.
*  PRIVATE SECTION.
*  DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zi_rfq_supsummary.

ENDCLASS.



CLASS ZBP_IDD_QUOTE_COMPARISON IMPLEMENTATION.
ENDCLASS.
