CLASS zbp_i_dd_supqtprice DEFINITION  PUBLIC  FINAL FOR BEHAVIOR OF zi_dd_supqtprice.

* CREATE PUBLIC .
*
*  PUBLIC SECTION.
*  PROTECTED SECTION.
*  PRIVATE SECTION.
ENDCLASS.



CLASS ZBP_I_DD_SUPQTPRICE IMPLEMENTATION.
ENDCLASS.
